### ISSUE TITLE
Todo 생성 기능

### ISSUE THREAD

**Issue by Seulgi-Yoo** [Seulgi-Yoo/pre-project-practice#3]
### 만들고자 하는 기능
Todo 생성 기능

### 해당 기능을 구현하기 위해 할 일

- [ ] json-server로 더미데이터 및 서버 생성
- [ ] state로 todo 관리
- [ ] 생성된 todo를 list에 렌더링

### 예상 작업 시간
1h
